### ISSUE TITLE
Bundle size comparison with webpack

### ISSUE THREAD

**Issue by YagoLopez** [adhrinae/ts-react-parcel#2]
Hello again.

I sent an issue some time ago, but now i have a question i would like to ask if you dont mind.

How is the comparison of file sizes with webpack... bigger, smaller? My first impression is parcel bundle is a little smaller than webpack but not sure at all. Could you confirm it or shed some light on the topic. I would like to know your impressions.

Thank you very much.

**Comment by adhrinae** [comment]
@YagoLopez
I appreciate your interests.

Since I don't have enough knowledge for proper comparison between Parcel and Webpack, I recommend you to look into [this repository](https://github.com/TheLarkInn/bundler-performance-benchmark).

In my opinion, the only(or the biggest) problem of Webpack is that it is very hard to configure for beginner(even for intermediate users if they want to optimize their build process).

Parcel team have been making so much effort to get rid of that problem. I think it's great and their future is bright.

I am expecting to find another great project built in Parcel bundler. then we can have deeper discussion about this topic.

**Comment by YagoLopez** [comment]
Cool, i'll take a look to the link you provided, By the way... I forked your Project for personal use here: https://github.com/YagoLopez/react-parcel

I solved a little problem I had with package.json develop script and added a couple of features. What about if I make a pull request and unify both repos in one?

**Comment by adhrinae** [comment]
Wow, That would be honor to me.

Anyhow I was thinking to update this repo someday. Your approach looks great.
Please make a PR so I can find a way merge your code elegantly.

FYI, I recommend you to add `.idea` folder to your `.gitignore`. It pollutes your own github repository. my `.vscode` folder has only few json files though.
For example, If you work with other contributors in that repository, every time you commit `.idea` folder's changes are going to be part of your commit as well, that makes conflict with the other's commit Even though that change has nothing to do with your implementation.

**Comment by YagoLopez** [comment]
Great!. Still not sure if  it would be better send a global PR as I have the code now. I send it and if you find something inapropiated, just dont merge whitout any problem.

I'll ignore .idea folder. I use it for config my IDE in following projects, but no problem ignoring it.

Now i'm a bit busy but I'll send it in a few days.

By the way the benchmarks are made by the Webpack creator if I'm not wrong. Maybe they are a bit biased lol :smile:. My impressions are: webpack compression ratio is better but a bit slower than Parcel. That has sense but havent figures to demonstrate it.
