### ISSUE TITLE
react-hot-loader is not required

### ISSUE THREAD

**Issue by Ciantic** [adhrinae/ts-react-parcel#4]
I'm learning about parcel, and was asking in Slack about this project.

I got information that this is not required at all:

```
import { hot } from 'react-hot-loader'
```

The parcel works with react-hot-loader out of the box, nothing is required to hook it. 

Secondly that is also wrong because it would bundle react-hot-loader to production build (bad) causing unnecessary dependency.

**Comment by adhrinae** [comment]
When I tried to update this project lately, my build had been failed because parcel's out-of-box HMR didn't working. So I adapted react-hot-loader [after reading this doc.](https://github.com/parcel-bundler/website/blob/master/src/i18n/en/docs/hmr.md)

I rechecked the project right after got your issue, somehow it works fine.
So I will update the project with updating dependencies and removing unnecessary settings.
Thank you for pointing this out.

**Comment by adhrinae** [comment]
And I found the reason why my build was failed at first time.
Looks like `Switch` is a kind of inappropriate name for React component. Perhaps reserved word or cause conflict with other internal APIs.

After I changed the name of `Switch` to something else, the error has gone.

**Comment by Ciantic** [comment]
Thanks for the reply, good to know, since I removed the components I didn't get errors either.

I also feel I'm building starter setups every year, they all seem to have different quirks. Duly hope the front-end tooling would finally get some stability!

**Comment by adhrinae** [comment]
That's right. I hope so. and also hope this setup would be helpful to you.

I wrote some example codes for practicing typescript with React and educational purpose. So Working demo is a kind of important to me.
